### ISSUE TITLE
Please cut a new release

### ISSUE THREAD

**Issue by johnpbloch** [lkwdwrd/wp-muplugin-loader#7]
After #6 has been merged, it'd be awesome if we could get another tagged release so we can require a "stable" version in Composer that also has the path normalization and unix separator forcing included.

**Comment by szepeviktor** [comment]
Yes.

**Comment by szepeviktor** [comment]
The latest commit is released!
https://github.com/lkwdwrd/wp-muplugin-loader/releases/tag/1.0.5

@johnpbloch You may close it.
